# Generated by Django 3.0.4 on 2020-04-10 12:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200331_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='login_user',
            field=models.CharField(db_index=True, default=django.utils.timezone.now, max_length=40, unique=True, verbose_name='Логин'),
            preserve_default=False,
        ),
    ]
