# Generated by Django 3.0.6 on 2020-05-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200510_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='login_user',
            field=models.CharField(db_index=True, max_length=40, verbose_name='Логин'),
        ),
    ]
