# Generated by Django 3.0.6 on 2020-05-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200511_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='login_user',
            field=models.CharField(db_index=True, max_length=40, unique=True, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='user_pics/default_user_icon.png', upload_to='user_pics/%Y/', verbose_name='Фотография'),
        ),
    ]
