# Generated by Django 2.2.9 on 2020-02-09 15:48

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('tag_image', models.FileField(blank=True, null=True, upload_to='categories/%Y/')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='users/%Y/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_pub', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('title_detail', models.CharField(db_index=True, max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('body', ckeditor.fields.RichTextField(blank=True, db_index=True)),
                ('article_image', models.FileField(blank=True, null=True, upload_to='posts/%Y/')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='polls.Tag')),
            ],
            options={
                'ordering': ('-date_pub',),
            },
        ),
    ]
