# Generated by Django 2.2.5 on 2019-11-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='article_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
