# Generated by Django 3.0.4 on 2020-04-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_post_title_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='publicate_in',
            field=models.CharField(choices=[('L', 'Лента'), ('B', 'Слайдер')], default='L', max_length=2, verbose_name='Тип публикации:'),
        ),
    ]
