# Generated by Django 2.2.5 on 2019-11-22 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20191107_0954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-date_pub',)},
        ),
        migrations.AddField(
            model_name='tag',
            name='tag_image',
            field=models.ImageField(blank=True, height_field='width', max_length=255, upload_to='media/tag', width_field='height'),
        ),
    ]
