# Generated by Django 3.0.4 on 2020-04-14 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0004_auto_20200412_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Комментарий')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('last_mod_time', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_enable', models.BooleanField(default=True, verbose_name='Активен')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Post', verbose_name='article')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Comment', verbose_name='main_comment')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['-created_time'],
                'get_latest_by': 'id',
            },
        ),
    ]
