# Generated by Django 2.2.5 on 2019-11-22 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20191122_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_image',
            field=models.ImageField(blank=True, height_field='200', max_length=255, upload_to='media/tag', width_field='200'),
        ),
    ]
