# Generated by Django 2.2.5 on 2019-11-22 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20191122_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
