# Generated by Django 2.2.7 on 2019-11-26 15:59

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20191122_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_detail',
            field=ckeditor.fields.RichTextField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
