# Generated by Django 2.2.7 on 2019-12-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='users/%Y/%m/'),
        ),
    ]
